# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-07 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_implementation_test', '0002_bankregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankregister',
            name='bank_account_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
